server:
  error:
    whitelabel:
      enabled: false
spring:  datasource:    url: jdbc:mysql://localhost:3306/backendninja?useSSL=false
    username: root
    password: Dna_031011
  jpa:    show-sql: true    hibernate:      ddl-auto: update      naming:        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  devtools:    restart:      log-condition-evaluation-delta: false      exclude: static/**,public/**
      